import Link from "next/link";
import Head from "next/head";
import { useSession } from "next-auth/client";
import Image from "next/image";
//import splogo from "../../public/images/spca-pv1.gif";
import prisma from "../../../lib/prisma.ts";
import pvarlogo from "../../../public/images/pvar2.gif";
//import Points from "../../components/points";
import { useEffect, useState } from "react";

// Start nes code
export async function getServerSideProps(context) {
  const { id } = context.params;
  const user = await prisma.user.findUnique({
    where: {
      id: parseInt(id),
    },
    include: {
      payments: true,
      points: true,
    },
  });
  return {
    props: {
      user,
      //payments: user.payments,
    },
  };
}

export default function EthDonate({ user }) {
  const [session] = useSession();

  let payResult = user.payments.map(({ amount }) => amount);
  let pointsResult = user.points.map(({ amount }) => amount);

  const totalPay = payResult.reduce(
    (previousValue, currentValue, index) => previousValue + currentValue,
    0
  );

  const totalPoint = pointsResult.reduce(
    (previousValue, currentValue, index) => previousValue + currentValue,
    0
  );

  if (!session) return <h1 className="py-10 px-20 text-3xl">Not Signed In!</h1>;
  <div className="page-nav">
    <p>&nbsp;</p>
  </div>;

  return (
    <div>
      <Head>
        <title>Ethereum Donation: {user.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-1/4 p-5 border-2 ml-5">
          <div className="mt-1">
            <Image
              className="rounded-lg"
              src={pvarlogo}
              alt="logo"
              width={270}
              height={231}
            />
          </div>
          <p>&nbsp;</p>
          <p>
            NFT Points Available:
            <br />
            <b>{totalPoint}</b>
          </p>
          <p>&nbsp;</p>
          <p>
            Donations To Date:
            <br />
            <b>${totalPay}</b>
          </p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
        </div>

        <div className="flex-auto w-3/4 p-5 ml-10 mr-10">
          <div className="text-center">
            <h1>Ethereum Donation: {user.name}!</h1>
          </div>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1>Form:</h1>
          <p>&nbsp;</p>
          ** Need ETH Converter
          <p>&nbsp;</p>
          <p>
            This is a very simple prototype form we will use to establish the
            payment flow, manage NFT Points, track donations, transfer NFTs to
            users who have setup their wallets, and more.
          </p>
          <p>&nbsp;</p>
        </div>
      </div>
    </div>
  );
}
