import Link from "next/link";
import Head from "next/head";
import prisma from "../../../lib/prisma.ts";

export default function NotesPage({ data }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/manager/notes/newNote">Add New Note</Link>
        </div>
        <p>&nbsp;</p>
        <h1 className="text-2xl font-black">All Notes</h1>
        <p>&nbsp;</p>

        <ul>
          {data.map((item) => (
            <li key="item.id">
              <b>{item.title}</b>
              <br />
              {item.notebody}
              <br />
              <p>Author: {item.author}</p>
              <p>ID: {item.id}</p>
              <div className="page-nav">
                <Link href={`/manager/notes/noteDetails/${item.id}`}>
                  Details
                </Link>
              </div>
              <br />
              &nbsp;
            </li>
          ))}
        </ul>
      </main>

      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const notes = await prisma.note.findMany();

  return {
    props: { data: notes },
  };
}
