import Link from "next/link";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/client";
import Image from "next/image";
import splogo from "../../public/images/spca-pv1.gif";
import { toast, ToastContainer } from "react-nextjs-toast";
import { useState } from "react";
import Router from "next/router";

export default function Pay() {
  const [session, loading] = useSession();
  const [formData, setFormData] = useState({});
  async function savePayment(e) {
    toast.notify(`Payment is processing!`);
    e.preventDefault();
    const response = await fetch("/api/pay/newpayment", {
      method: "POST",
      body: JSON.stringify(formData),
    });
    toast.remove();
    return await response.json(), await Router.push("/");
  }

  return (
    <div>
      <Head>
        <title>Donate to SPCAPV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-1/4 p-5 border-2 ml-5">
          <div className="mt-1">
            <Image
              className="rounded-lg"
              src={splogo}
              alt="logo"
              width={150}
              height={127}
            />
          </div>
          <p>&nbsp;</p>
          <p>NFT Points Available: </p>
          <p>Dashboard</p>
          <p>Donations To Date: </p>
          <p>History</p>
          <p>More...</p>
        </div>

        <div className="flex-auto w-3/4 p-5 ml-10 mr-10">
          <div className="text-center">
            <h1>Donate</h1>
          </div>
          <p>&nbsp;</p>
          <h1>Put Form Here! {session && session.user.uid}</h1>
          <p>&nbsp;</p>
          <form className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
            <input
              type="hidden"
              name="ownerId"
              defaultValue="{{session && session.user.uid}}"
              onChange={(e) =>
                setFormData({ ...formData, ownerId: e.target.value })
              }
            />
            <p>
              <b>First and Last Name (for your records)</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="First and Last Name"
                name="pmtName"
                onChange={(e) =>
                  setFormData({ ...formData, pmtName: e.target.value })
                }
              />
            </p>
            <p>
              <b>Amount of Donation</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Amount - i.e. $50.00"
                name="amount"
                onChange={(e) =>
                  setFormData({ ...formData, amount: e.target.value })
                }
              />
            </p>
            <p>
              <b>Currency Type (i.e. USD, CAD)</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Currency Type - i.e. USD, CAD"
                name="currencyType"
                onChange={(e) =>
                  setFormData({ ...formData, currencyType: e.target.value })
                }
              />
            </p>
            <p>
              <b>Method of Payment</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Method of Payment - i.e. PayPal, Credit Card"
                name="methodOfPayment"
                onChange={(e) =>
                  setFormData({ ...formData, methodOfPayment: e.target.value })
                }
              />
            </p>
            <p>
              <b>Notes</b>
              <br />
              <textarea
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
                name="notes"
                id=""
                cols="40"
                rows="5"
                placeholder="Type your notes about this donation here."
                onChange={(e) =>
                  setFormData({ ...formData, notes: e.target.value })
                }
              />
            </p>

            <p>&nbsp;</p>
            <ToastContainer />
            <p>
              <button
                onClick={savePayment}
                className="font-bold mt-4 bg-pink-500 text-white rounded p-4 shadow-lg"
              >
                Send Payment
              </button>
            </p>
          </form>
          <p>&nbsp;</p>
          <p>
            This is a very simple prototype form we will use to establish the
            payment flow, manage NFT Points, track donations, transfer NFTs to
            users who have setup their wallets, and more.
          </p>
          <p>&nbsp;</p>
          <p>
            Lorem Ipsum is simply dummy text of the printing and typesetting
            industry. Lorem Ipsum has been the industry standard dummy text ever
            since the 1500s, when an unknown printer took a galley of type and
            scrambled it to make a type specimen book. It has survived not only
            five centuries, but also the leap into electronic typesetting,
            remaining essentially unchanged. It was popularised in the 1960s
            with the release
          </p>
        </div>
      </div>
    </div>
  );
}
