import Link from "next/link";
import Head from "next/head";
import { useSession } from "next-auth/client";
import Image from "next/image";
import splogo from "../../public/images/spca-pv1.gif";
import { toast, ToastContainer } from "react-nextjs-toast";
import { useState, useRef } from "react";
import Router from "next/router";

// Start nes code
export default function Pay() {
  const formRef = useRef();
  const [disable, setDisable] = useState(false);
  const [session] = useSession();

  async function savePayment() {
    setDisable(true);
    const {
      //editContractId,
      editPmtName,
      editAmount,
      editCurrencyType,
      editMethodOfPayment,
      editNotes,
    } = formRef.current;

    const createdBy = parseInt(session.user.uid);
    const ownerId = parseInt(session.user.uid);
    const pmtName = editPmtName.value;
    const amount = editAmount.value;
    const currencyType = editCurrencyType.value;
    const methodOfPayment = editMethodOfPayment.value;
    const notes = editNotes.value;

    //
    let formData = {
      createdBy,
      ownerId,
      pmtName,
      amount,
      currencyType,
      methodOfPayment,
      notes,
    };

    // End new code

    toast.notify(`Payment is processing!`);
    const response = await fetch("/api/pay/newpayment", {
      method: "POST",
      body: JSON.stringify(formData),
    });

    const added = await response.json();
    console.log("JSON reply: ", added);
    const pmtid = added.id;

    // GET THE PAYMENT ID

    const paymentId = pmtid;

    //
    let theData = {
      ownerId,
      paymentId,
      amount,
      notes,
      createdBy,
    };

    await fetch(`/api/pay/newpoints`, {
      method: "POST",
      body: JSON.stringify(theData),
    });

    toast.remove();
    return await Router.push(`/profile/${ownerId}`);
  }

  return (
    <div>
      <Head>
        <title>Donate to SPCAPV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-1/4 p-5 border-2 ml-5">
          <div className="mt-1">
            <Image
              className="rounded-lg"
              src={splogo}
              alt="logo"
              width={150}
              height={127}
            />
          </div>
          <p>&nbsp;</p>
          <p>NFT Points Available: </p>
          <p>Dashboard</p>
          <p>Donations To Date: </p>
          <p>History</p>
          <p>More...</p>
        </div>

        <div className="flex-auto w-3/4 p-5 ml-10 mr-10">
          <div className="text-center">
            <h1>Donation Form</h1>
          </div>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <p>
              <b>First and Last Name (for your records)</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="First and Last Name"
                defaultValue=""
                name="editPmtName"
                required
              />
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Amount of Donation</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Amount - i.e. $50.00"
                defaultValue=""
                name="editAmount"
                required
              />
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Currency Type (i.e. USD, CAD)</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Currency Type - i.e. USD, CAD"
                defaultValue=""
                name="editCurrencyType"
                required
              />
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Method of Payment</b>
              <br />
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                type="text"
                placeholder="Method of Payment - i.e. PayPal, Credit Card"
                defaultValue=""
                name="editMethodOfPayment"
                required
              />
            </p>
            <p>&nbsp;</p>
            <p>
              <b>Notes</b>
              <br />
              <textarea
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
                name="editNotes"
                cols="40"
                rows="5"
                placeholder="Type your notes about this donation here."
                defaultValue=""
              />
            </p>

            <p>&nbsp;</p>
            <ToastContainer />
            <p>
              <p>&nbsp;</p>
              <button
                className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
                disabled={disable}
                onClick={() => savePayment()}
              >
                Send Payment
              </button>
            </p>
          </form>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>
            This is a very simple prototype form we will use to establish the
            payment flow, manage NFT Points, track donations, transfer NFTs to
            users who have setup their wallets, and more.
          </p>
          <p>&nbsp;</p>
        </div>
      </div>
    </div>
  );
}
