import { useState, useRef } from "react";
import Head from "next/head";
import Router from "next/router";
import prisma from "../../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const user = await prisma.user.findUnique({ where: { id: parseInt(id) } });
  if (user.admin == true) {
    user.admin = "on";
  }
  return {
    props: {
      user,
    },
  };
}

export default function EditUser({ user }) {
  const formRef = useRef();
  const [disable, setDisable] = useState(false);

  async function editUser() {
    setDisable(true);
    const { editPassword } = formRef.current;
    const password = editPassword.value;

    //
    let formData = {
      password,
    };

    await fetch(`/api/users/changePassword/${user.id}`, {
      method: "PUT",
      body: JSON.stringify(formData),
    });
    setDisable(false);
    Router.push("/manager/users");
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Change Password: {user?.name} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <div>
            <p>&nbsp;</p>
            <div className="page-nav">
              <h3>Change User Password: {user?.name} </h3>
            </div>
          </div>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <div className="label">
              <label>Password</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={user?.password}
                name="editPassword"
                type="text"
              />
              <p>&nbsp;</p>
            </div>
          </form>
        </div>
        <div>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            disabled={disable}
            onClick={() => editUser()}
          >
            Save New Password
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
