import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
import prisma from "../../../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const contract = await prisma.contract.findUnique({
    where: { id: parseInt(id) },
  });
  return {
    props: {
      contract,
    },
  };
}

async function deleteContract(id) {
  await fetch(`/api/notes/noteDelete/${id}`, {
    method: "DELETE",
  });
  Router.push("/notes");
}

export default function ContractView(props) {
  //const router = useRouter();
  const { contract } = props;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{contract.contractName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Name: {contract.contractName}</p>
        <p>&nbsp;</p>
        Body:
        <br />
        <p>{contract.tokenSymbol}</p>
        <div className="page-nav">
          <Link href={`/notes/editNote/${contract.id}`}>Edit</Link>- &nbsp;
          <button
            className="delete button"
            onClick={() => {
              const confirmBox = window.confirm(
                "Do you really want to delete this Contract?"
              );
              if (confirmBox === true) {
                deleteContract(contract.id);
              }
            }}
          >
            Delete
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
