import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
import prisma from "../../../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const contract = await prisma.contract.findUnique({
    where: { id: parseInt(id) },
  });
  return {
    props: {
      contract,
    },
  };
}

async function deleteContract(id) {
  await fetch(`/api/notess/noteDelete/${id}`, {
    method: "DELETE",
  });
  Router.push("/notes");
}

export default function ContractView(props) {
  //const router = useRouter();
  const { contract } = props;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{contract.contractName}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Name: {contract.contractName}</p>
        <p>Token Type: {contract.tokenType}</p>
        <p>Address: {contract.address}</p>
        <p>Token Name: {contract.tokenName}</p>
        <p>Token Symbol: {contract.tokenSymbol}</p>
        <p>Network: {contract.network}</p>
        <p>EtherScan Url: {contract.scanUrl}</p>
        <p>Owner Address: {contract.ownerAddress}</p>
        <p>User: ??</p>
        <p>Owner ID: {contract.ownerId}</p>
        <p>Description: {contract.description}</p>
        <p>Notes: {contract.notes}</p>
        <p>Created At: {contract.createdAt.toDateString()}</p>
        <p>Created By: {contract.createdBy}</p>
        <p>Updated At: {contract.updatedAt.toDateString()}</p>
        <p>Updated By: {contract.updatedBy}</p>
        <p>Deleted?: {contract.deleted}</p>
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href={`/manager/nfts/contracts/editContract/${contract.id}`}>
            Edit
          </Link>
          - &nbsp;
          <button
            className="delete button"
            onClick={() => {
              const confirmBox = window.confirm(
                "Do you really want to delete this Contract?"
              );
              if (confirmBox === true) {
                deleteContract(contract.id);
              }
            }}
          >
            Delete
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
