import { signIn, signOut, useSession } from "next-auth/client";
import Image from "next/image";
//import shelter from "../../../../public/images/shelter-river.png";
import splogo from "../../../../public/images/spca-pv1.gif";
import Link from "next/link";
import Head from "next/head";
import prisma from "../../../../lib/prisma.ts";
//import mydog from "../../../../public"

export default function Page({ data }) {
  const [session, loading] = useSession();

  return (
    <div>
      <Head>
        <title>Tokens</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-full flex flex-col sm:flex-row flex-grow overflow-hidden">
        <div className="sm:w-1/3 md:1/4 w-full flex-shrink flex-grow-0 p-4">
          <div className="sticky top-0 p-4 w-full">
            <div className="mt-0">
              <Image
                className="rounded-lg"
                src={splogo}
                alt="logo"
                width={150}
                height={127}
              />
            </div>
            <p>&nbsp;</p>
            <ul className="flex sm:flex-col overflow-hidden content-center justify-between">
              <Link href="/manager/nfts/contracts">Contracts</Link>
              <Link href="/manager/nfts/tokens">Tokens</Link>
              <Link href="/manager/nfts/transactions">Transactions</Link>
              <Link href="/manager/nfts/payments">Payments</Link>
            </ul>
          </div>
        </div>
        <main
          role="main"
          className="w-3/4 mr-10 h-full flex-grow p-3 overflow-auto"
        >
          <p>&nbsp;</p>
          <p className="font-black text-4xl">Token Administration</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          {data.map((item) => (
            <div
              key="item.id"
              className="max-w-sm w-full lg:max-w-full lg:flex my-5"
            >
              <Link href={`/manager/nfts/tokens/detailsToken/${item.id}`}>
                <div
                  className="h-48 lg:h-auto lg:w-48 flex-none bg-cover 
                rounded-t lg:rounded-t-none lg:rounded-l text-center overflow-hidden"
                  style={{
                    ...(item.metaImageUrl
                      ? {
                          backgroundImage: `url(${item.metaImageUrl})`,
                        }
                      : {}),
                  }}
                  title="NFT Image"
                >
                  <span className="card" style={{ display: "block" }}></span>
                </div>
              </Link>

              <div className="w-full border-r border-b border-l border-gray-400 lg:border-l-0 lg:border-t lg:border-gray-400 bg-white rounded-b lg:rounded-b-none lg:rounded-r p-4 flex flex-col justify-between leading-normal">
                <div className="mb-8">
                  <p className="text-sm text-gray-600 flex items-center">
                    Token ID: {item.tokenId}
                  </p>
                  <p>&nbsp;</p>
                  <div className="text-gray-900 font-bold text-xl mb-2">
                    {item.metaName}
                  </div>
                  <p className="text-gray-700 text-base">
                    {item.metaDescription}
                  </p>
                  <p>&nbsp;</p>
                  <p>For Sale: &nbsp; {item.forSale}</p>
                  <div className="page-nav">
                    <Link href={`/manager/nfts/tokens/detailsToken/${item.id}`}>
                      Details
                    </Link>
                  </div>
                </div>
              </div>
            </div>
          ))}

          <hr />
          <p>&nbsp;</p>
          <p className="font-black text-3xl">
            This section will be developed under a new git branch before it is
            released. The branch will be named nftdatabase.
          </p>
          <p>&nbsp;</p>
        </main>
      </div>
      <footer className="bg-yellow-100 mt-auto font-black text-center">
        SPCAPV Footer!!
      </footer>
    </div>
  );
}

export async function getServerSideProps() {
  const tokens = await prisma.token.findMany({
    orderBy: [
      {
        createdAt: "desc",
      },
    ],
  });

  return {
    props: { data: tokens },
  };
}
