import Link from "next/link";
import Head from "next/head";
import prisma from "../../../lib/prisma.ts";
import { session, signIn, signOut, useSession } from "next-auth/client";
import { useRouter } from "next/router";
//const router = useRouter();

export default function Gallery({ data }) {
  const [session, loading] = useSession();
  //const myparamid = req.query.id;
  const router = useRouter();
  const myparamid = router.query.id;
  if (!session) return <h1 className="py-10 px-20 text-3xl">Not Signed In!</h1>;
  <div className="page-nav">
    <p>&nbsp;</p>
  </div>;

  if (session && myparamid != session.user.uid)
    return <h1 className="py-10 px-20 text-3xl">Nope! Bad idea!</h1>;
  <div className="page-nav">
    <p>&nbsp;</p>
  </div>;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>My NFT Collection</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex p-4">
        <div className="px-4" style={{ maxWidth: "1600px" }}>
          {session && (
            <div className="page-nav">
              <Link href="/">Put Links Here</Link> -
              <Link href="/">More Links</Link> -
            </div>
          )}
          <div>
            <p>&nbsp;</p>
            <h1>My NFT Collection - Display Yes</h1>
            <p>&nbsp;</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-4">
            {data.map((nft, i) => (
              <div key={i} className="border shadow rounded-xl overflow-hidden">
                <Link href={`/gallery/nftDetails/${nft.id}`}>
                  <a>
                    <img src={nft.metaImageUrl} />
                  </a>
                </Link>
                <div className="p-4">
                  <p
                    style={{ height: "64px" }}
                    className="text-2xl font-semibold"
                  >
                    {nft.metaName}
                  </p>
                  <div style={{ height: "70px", overflow: "hidden" }}>
                    <p className="text-gray-400">{nft.metaDescription}</p>
                  </div>
                </div>
                <div className="p-4 bg-black">
                  <p className="text-2xl mb-4 font-bold text-white">
                    Something Here..
                  </p>
                  <button className="w-full bg-pink-500 text-white font-bold py-2 px-12 rounded">
                    Details
                  </button>
                </div>
                <div className="page-nav">
                  <p>&nbsp;</p>
                  <Link href={`/gallery/nftDetails/${nft.id}`}>
                    <a>NFT Details</a>
                  </Link>
                  <br />
                </div>
                <div className="text-xs">
                  Display: {nft.display && "Yes"}
                  <br />
                  For Sale: {nft.forSale && "Yes"}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const { id } = context.params;
  const nfts = await prisma.token.findMany({
    where: { display: true, ownerId: parseInt(id) },
  });

  return {
    props: { data: nfts },
  };
}
