import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
const { ethers } = require("ethers");

import data from "../../data4.json";

const flog = Buffer.from(data.encodedLogs, "base64");
const fflog = flog.toString();

// 146 and 215
// should be 148 and 214
const firstat = fflog.indexOf("@@") + 2;
const lastat = fflog.lastIndexOf("@@");

// Put @ signs in my console log.
var res = fflog.substring(firstat, lastat);

const tokenId = parseInt(res, 16);

//const added = await response.json();
//const data = added.data;

export default function MyLog() {
  //const router = useRouter();
  //const { note } = props;

  return (
    <div>
      <Head>
        <title>My Log</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-3/4 p-5 border-2 ml-0 mr-10">
          <p>Title: My Log</p>
          <p>&nbsp;</p>
          Processed Encoded Logs:
          <br />
          <p className="break-words"> {fflog}</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p className="break-words">
            Index of At Signs
            <br />
            {firstat}, {lastat}
          </p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p className="break-words">SubString: {res}</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p className="break-words">Token ID: {tokenId}</p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p className="break-words">
            Data.EncodedLogs - Not Processed
            <br />
            {data.encodedLogs}
          </p>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <div className="page-nav">
            <Link href="/">Edit</Link>- &nbsp;
          </div>
        </div>
      </div>
    </div>
  );
}
