import Link from "next/link";
import Head from "next/head";
//import prisma from "../../lib/prisma.ts";

export default function Success({ data }) {
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>NFT Success</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href="/oz/sendNftOnly">Add New NFT</Link>
        </div>
        <p>&nbsp;</p>
        <h1 className="text-3xl font-black">SUCCESS !</h1>
        <p>&nbsp;</p>
      </main>

      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
