import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
import prisma from "../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const note = await prisma.note.findUnique({ where: { id: parseInt(id) } });
  if (note.publish == true) {
    note.publish = "true";
  }
  return {
    props: {
      note,
    },
  };
}

async function deleteNote(id) {
  await fetch(`/api/notes/noteDelete/${id}`, {
    method: "DELETE",
  });
  Router.push("/notes");
}

export default function Note(props) {
  //const router = useRouter();
  const { note } = props;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{note.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Title: {note.title}</p>
        <p>&nbsp;</p>
        Body:
        <br />
        <p>{note.notebody}</p>
        <p>&nbsp;</p>
        <p>Publish: {note.publish}</p>
        <p>&nbsp;</p>
        <div className="page-nav">
          <Link href={`/notes/editNote/${note.id}`}>Edit</Link>- &nbsp;
          <button
            className="delete button"
            onClick={() => {
              const confirmBox = window.confirm(
                "Do you really want to delete this Note?"
              );
              if (confirmBox === true) {
                deleteNote(note.id);
              }
            }}
          >
            Delete
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
