import Link from "next/link";
import Head from "next/head";
import prisma from "../../lib/prisma.ts";
import { signIn, signOut, useSession } from "next-auth/client";

export default function Gallery({ data }) {
  const [session, loading] = useSession();
  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>NFT Gallery - SPCAPV</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex p-4">
        <div className="px-4" style={{ maxWidth: "1600px" }}>
          {session && session.user.admin && (
            <div className="page-nav">
              <Link href="/market">For Sale</Link> -
              <Link href="/market/create-item">Create Item</Link> -
              <Link href="/market/my-assets">My Assets</Link> -
              <Link href="/market/creator-dashboard">Dashboard</Link>
            </div>
          )}
          <div>
            <p>&nbsp;</p>
            <h1>NFT Gallery - SPCAPV!</h1>
            <p>&nbsp;</p>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4 pt-4">
            {data.map((nft, i) => (
              <div key={i} className="border shadow rounded-xl overflow-hidden">
                <Link href={`/gallery/nftDetails/${nft.id}`}>
                  <a>
                    <img src={nft.metaImageUrl} />
                  </a>
                </Link>
                <div className="p-4">
                  <p
                    style={{ height: "64px" }}
                    className="text-2xl font-semibold"
                  >
                    {nft.metaName}
                  </p>
                  <div style={{ height: "70px", overflow: "hidden" }}>
                    <p className="text-gray-400">{nft.metaDescription}</p>
                  </div>
                </div>
                <div className="p-4 bg-black">
                  <p className="text-2xl mb-4 font-bold text-white">
                    Something Here..
                  </p>
                  <button className="w-full bg-pink-500 text-white font-bold py-2 px-12 rounded">
                    Details
                  </button>
                </div>
                <div className="page-nav">
                  <p>&nbsp;</p>
                  <Link href={`/gallery/nftDetails/${nft.id}`}>
                    <a>NFT Details</a>
                  </Link>
                  <br />
                </div>
                <div className="text-xs">
                  Display: {nft.display && "Yes"}
                  <br />
                  For Sale: {nft.forSale && "Yes"}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

export async function getServerSideProps() {
  const nfts = await prisma.token.findMany({
    where: { display: true },
  });

  return {
    props: { data: nfts },
  };
}
