import Link from "next/link";
import Head from "next/head";
import { useSession } from "next-auth/client";
import Image from "next/image";
import splogo from "../../public/images/spca-pv1.gif";
import prisma from "../../lib/prisma.ts";
//import Points from "../../components/points";
import { useEffect, useState } from "react";

// Start nes code
export async function getServerSideProps(context) {
  const { id } = context.params;
  const user = await prisma.user.findUnique({
    where: {
      id: parseInt(id),
    },
    include: {
      payments: true,
      points: true,
    },
  });
  return {
    props: {
      user,
      //payments: user.payments,
    },
  };
}

export default function ProfileHome({ user }) {
  const [session] = useSession();

  let payResult = user.payments.map(({ amount }) => amount);
  let pointsResult = user.points.map(({ amount }) => amount);

  const totalPay = payResult.reduce(
    (previousValue, currentValue, index) => previousValue + currentValue,
    0
  );

  const totalPoint = pointsResult.reduce(
    (previousValue, currentValue, index) => previousValue + currentValue,
    0
  );

  return (
    <div>
      <Head>
        <title>Dashboard: {user.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-1/4 p-5 border-2 ml-5">
          <div className="mt-1">
            <Image
              className="rounded-lg"
              src={splogo}
              alt="logo"
              width={150}
              height={127}
            />
          </div>
          <p>&nbsp;</p>
          <p>
            NFT Points Available:
            <br />
            <b>{totalPoint}</b>
          </p>
          <p>&nbsp;</p>
          <p>
            Donations To Date:
            <br />
            <b>${totalPay}</b>
          </p>
          <p>&nbsp;</p>
          <div className="page-nav p-2">
            <Link href="/oz/sendNftOnly" passHref>
              <b>
                <a>Send NFT Only</a>
              </b>
            </Link>
          </div>
          <p>&nbsp;</p>
          <div className="page-nav p-2">
            <Link href="/profile/createNewNft" passHref>
              <b>
                <a>Create New NFT - With Relay!</a>
              </b>
            </Link>
          </div>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <div className="page-nav p-2">
            <Link href="/oz/fixjson" passHref>
              <b>
                <a> Fix JSON!</a>
              </b>
            </Link>
          </div>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>Dashboard</p>
          <p>History</p>
          <p>More...</p>
        </div>

        <div className="flex-auto w-3/4 p-5 ml-10 mr-10">
          <div className="text-center">
            <h1>Profile: {user.name}!</h1>
          </div>
          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <h1>Payments:</h1>
          <p>&nbsp;</p>
          <ul>
            {user.payments.map((item) => (
              <li key={item.id}>
                Payment Name: <b>{item.pmtName}</b>
                <br />
                Owner User: <b>{user.name}</b>
                <br />
                AMOUNT: {item.amount}
                <br />
                <p>Dated Received: {item.dateReceived.toLocaleString()}</p>
                &nbsp;
              </li>
            ))}
          </ul>

          <h1>NFT Points:</h1>
          <p>&nbsp;</p>
          <ul>
            {user.points.map((point) => (
              <li key={point.id}>
                Payment ID: <b>{point.paymentId}</b>
                <br />
                Notes: <b>{point.notes}</b>
                <br />
                AMOUNT: {point.amount}
                <br />
                <p>Dated Received: {point.dateReceived.toLocaleString()}</p>
                &nbsp;
              </li>
            ))}
          </ul>

          <p>&nbsp;</p>
          <p>
            This is a very simple prototype form we will use to establish the
            payment flow, manage NFT Points, track donations, transfer NFTs to
            users who have setup their wallets, and more.
          </p>
          <p>&nbsp;</p>
        </div>
      </div>
    </div>
  );
}
