import Link from "next/link";
import Head from "next/head";
import { useSession } from "next-auth/client";
import Image from "next/image";
import splogo from "../../public/images/spca-pv1.gif";
import prisma from "../../lib/prisma.ts";

// Start nes code
export async function getServerSideProps(context) {
  const { id } = context.params;
  const guest = await prisma.user.findUnique({ where: { id: parseInt(id) } });
  return {
    props: {
      guest,
    },
  };
}

export default function ProfileHome({ guest }) {
  //const formRef = useRef();
  //const [disable, setDisable] = useState(false);
  const [session] = useSession();

  return (
    <div>
      <Head>
        <title>Dashboard: {guest.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex h-full my-10">
        <div className="flex-auto w-1/4 p-5 border-2 ml-5">
          <div className="mt-1">
            <Image
              className="rounded-lg"
              src={splogo}
              alt="logo"
              width={150}
              height={127}
            />
          </div>
          <p>&nbsp;</p>
          <p>NFT Points Available: </p>
          <p>Dashboard</p>
          <p>Donations To Date: </p>
          <p>History</p>
          <p>More...</p>
        </div>

        <div className="flex-auto w-3/4 p-5 ml-10 mr-10">
          <div className="text-center">
            <h1>Profile: {guest.name}!</h1>
          </div>
          <p>&nbsp;</p>
          <h1>Put Form Here! {session && session.user.uid}</h1>
          <p>&nbsp;</p>

          <p>&nbsp;</p>
          <p>&nbsp;</p>
          <p>
            This is a very simple prototype form we will use to establish the
            payment flow, manage NFT Points, track donations, transfer NFTs to
            users who have setup their wallets, and more.
          </p>
          <p>&nbsp;</p>
        </div>
      </div>
    </div>
  );
}
