import Link from "next/link";
import React from "react";
import Router from "next/router";
import Head from "next/head";
import prisma from "../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const user = await prisma.user.findUnique({ where: { id: parseInt(id) } });
  return {
    props: {
      user,
    },
  };
}

async function deleteUser(id) {
  await fetch(`/api/users/userDelete/${id}`, {
    method: "DELETE",
  });
  Router.push("/users");
}

export default function User(props) {
  const { user } = props;

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>{user.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <p>Name: {user.name}</p>
        <p>Email: {user.email}</p>
        <p>Username: {user.username}</p>
        <p>Created: {user.createdAt.toDateString()}</p>
        <p>Updated: {user.updatedAt.toDateString()}</p>
        <p>Administrator: {user.admin && "Yes"}</p>
        <p>ID: {user.id}</p>
        <div className="page-nav">
          <Link href={`/users/editUser/${user.id}`}>Edit</Link>- &nbsp;
          <button
            className="delete button"
            onClick={() => {
              const confirmBox = window.confirm(
                "Do you really want to delete this Note?"
              );
              if (confirmBox === true) {
                deleteUser(user.id);
              }
            }}
          >
            Delete
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
