import { useState, useRef } from "react";
import Head from "next/head";
import Router from "next/router";
import prisma from "../../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const user = await prisma.user.findUnique({ where: { id: parseInt(id) } });
  if (user.admin == true) {
    user.admin = "on";
  }
  return {
    props: {
      user,
    },
  };
}

export default function EditUser({ user }) {
  const formRef = useRef();
  const [disable, setDisable] = useState(false);

  async function editUser() {
    setDisable(true);
    const {
      editUserName,
      editFirstName,
      editLastName,
      editUserEmail,
      editUserAdmin,
    } = formRef.current;
    const name = editUserName.value;
    const firstName = editFirstName.value;
    const lastName = editLastName.value;
    const email = editUserEmail.value;
    const admin = editUserAdmin.checked;
    const id = parseInt(user.id);

    //
    let formData = {
      name,
      firstName,
      lastName,
      email,
      admin,
    };

    await fetch(`/api/users/updateuser/${id}`, {
      method: "PUT",
      body: JSON.stringify(formData),
      //id: parseInt(id),
      //title: title,
      //notebody: notebody,
      //author: author
    });
    setDisable(false);
    Router.push("/manager/users");
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Edit: {user?.name} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <div>
            <p>&nbsp;</p>
            <div className="page-nav">
              <h3>Edit User</h3>
            </div>
          </div>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <div className="label">
              <label>Name</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={user?.name}
                name="editUserName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>First Name</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={user?.firstName}
                name="editFirstName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Last Name</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={user?.lastName}
                name="editLastName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Email</label>
              <br />
            </div>
            <div>
              <textarea
                defaultValue={user?.email}
                name="editUserEmail"
                type="textarea"
                rows="4"
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              ></textarea>
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Administrator</label>
              <br />
            </div>
            <div>
              <input
                className="form-checkbox"
                defaultChecked={user?.admin}
                name="editUserAdmin"
                type="checkbox"
              />
              <p>&nbsp;</p>
            </div>
          </form>
        </div>
        <div>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            disabled={disable}
            onClick={() => editUser()}
          >
            Save
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
