import { useState, useRef } from "react";
import Head from "next/head";
import Router from "next/router";
import prisma from "../../../../../lib/prisma.ts";

export async function getServerSideProps(context) {
  const { id } = context.params;
  const contract = await prisma.contract.findUnique({
    where: { id: parseInt(id) },
  });
  return {
    props: {
      contract,
    },
  };
}

export default function EditContract({ contract }) {
  const formRef = useRef();
  const [disable, setDisable] = useState(false);

  async function editContract() {
    setDisable(true);
    const {
      editContractName,
      editTokenType,
      editTokenSymbol,
      editTokenName,
      editNetwork,
      editAddress,
      editScanUrl,
      editOwnerAddress,
      editOwnerId,
      editDescription,
      editNotes,
    } = formRef.current;
    const contractName = editContractName.value;
    const tokenType = editTokenType.value;
    const network = editNetwork.value;
    const address = editAddress.value;
    const tokenName = editTokenName.value;
    const tokenSymbol = editTokenSymbol.value;
    const scanUrl = editScanUrl.value;
    const ownerAddress = editOwnerAddress.value;
    const ownerId = editOwnerId.value;
    const description = editDescription.value;
    const notes = editNotes.value;
    const id = parseInt(contract.id);

    //
    let formData = {
      contractName,
      tokenType,
      tokenName,
      tokenSymbol,
      network,
      address,
      scanUrl,
      ownerAddress,
      ownerId,
      description,
      notes,
    };

    await fetch(`/api/manager/nfts/contracts/updateContract/${id}`, {
      method: "PUT",
      body: JSON.stringify(formData),
    });
    setDisable(false);
    Router.push("/manager/nfts/contracts");
  }

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Edit: {contract?.contractName} </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <div>
          <div>
            <p>&nbsp;</p>
            <div className="page-nav">
              <h3>Edit Contract</h3>
            </div>
          </div>
          <form
            ref={formRef}
            className="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4"
          >
            <div className="label">
              <label>Contract Name</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.contractName}
                name="editContractName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Token Type</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.tokenType}
                name="editTokenType"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Token Name</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.tokenName}
                name="editTokenName"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Token Symbol</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.tokenSymbol}
                name="editTokenSymbol"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Contract Network Address</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.address}
                name="editAddress"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Network</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.network}
                name="editNetwork"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Etherscan URL</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.scanUrl}
                name="editScanUrl"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Owner Wallet Address</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.ownerAddress}
                name="editOwnerAddress"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Owner User ID</label>
              <br />
            </div>
            <div>
              <input
                className="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                defaultValue={contract?.ownerId}
                name="editOwnerId"
                type="text"
              />
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Description</label>
              <br />
            </div>
            <div>
              <textarea
                defaultValue={contract?.description}
                name="editDescription"
                type="textarea"
                rows="4"
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              ></textarea>
              <p>&nbsp;</p>
            </div>

            <div className="label">
              <label>Notes</label>
              <br />
            </div>
            <div>
              <textarea
                defaultValue={contract?.notes}
                name="editNotes"
                type="textarea"
                rows="4"
                className="w-full px-3 py-2 text-gray-700 border rounded-lg focus:outline-none"
              ></textarea>
              <p>&nbsp;</p>
            </div>
          </form>
        </div>
        <div>
          <button
            className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
            disabled={disable}
            onClick={() => editContract()}
          >
            Save
          </button>
        </div>
      </main>
      <footer className="text-center font-bold text-xl">
        <b>Powered by John Dunnicliffe</b>
      </footer>
    </div>
  );
}
